# -*- coding: utf-8 -*-
"""model_development.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHNfpoao6pa-ia3lHSBruuEgBFT15CuY
"""

# ===== STEP 1: IMPORT & LOAD DATASET =====
import pandas as pd
import numpy as np

# Load dataset (update filename if different)
file_path = "loan_data.csv"
df = pd.read_csv(file_path)

print("Dataset loaded successfully.")
print("Shape:", df.shape)
print("Columns:", list(df.columns))
print("\nPreview:")
print(df.head())

# Check if target column exists
if 'Status' not in df.columns and 'status' not in df.columns:
    raise KeyError("Target column 'Status' not found in dataset.")
else:
    print("\nTarget column found.")

# ===== STEP 2: DATA CLEANING =====
import numpy as np

# Drop duplicates
df = df.drop_duplicates().reset_index(drop=True)

# Normalize column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Handle missing values
num_cols = df.select_dtypes(include=[np.number]).columns
cat_cols = df.select_dtypes(include=['object']).columns

# Fill numeric columns with median
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Fill categorical columns with mode
for col in cat_cols:
    if not df[col].mode().empty:
        df[col] = df[col].fillna(df[col].mode()[0])

# Ensure target column 'status' exists and is integer
if 'status' not in df.columns:
    raise KeyError("Column 'status' not found after cleaning.")
df['status'] = pd.to_numeric(df['status'], errors='coerce').fillna(0).astype(int)

# Summary
print("Data Cleaning Completed.")
print("Shape after cleaning:", df.shape)
print("Total missing values:", df.isnull().sum().sum())
print("\nTarget distribution:")
print(df['status'].value_counts())

# Save cleaned copy for reference
df.to_csv("cleaned_stage2.csv", index=False)
print("\nSaved intermediate cleaned dataset as 'cleaned_stage2.csv'")

# ===== STEP 3: DROP LEAK / POST-DECISION COLUMNS =====
leak_cols = [
    'approv_in_adv', 'loan_limit', 'secured_by', 'security_type',
    'interest_rate_spread', 'upfront_charges', 'rate_of_interest',
    'submission_of_application'
]

# Only keep those that exist in df
to_drop = [c for c in leak_cols if c in df.columns]
df = df.drop(columns=to_drop, errors='ignore').copy()

print("Dropped columns:", to_drop)
print("New shape:", df.shape)

# Save cleaned dataset without leaks
df.to_csv("cleaned_no_leak.csv", index=False)
print("Saved cleaned dataset as 'cleaned_no_leak.csv'")

# ===== STEP 4: PREPROCESSING PIPELINE =====
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
import pickle

# Separate numeric and categorical columns
num_cols = df.select_dtypes(include=['int64','float64']).columns.drop('status', errors='ignore')
cat_cols = df.select_dtypes(include=['object']).columns

# Numeric pipeline: impute median, scale
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Categorical pipeline: impute mode, one-hot encode
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

# Combine into one ColumnTransformer
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

# Fit preprocessor once
preprocessor.fit(df.drop(columns=['status'], errors='ignore'))

# Save the fitted preprocessor and metadata
meta = {
    "preprocessor": preprocessor,
    "num_cols": list(num_cols),
    "cat_cols": list(cat_cols),
    "raw_feature_order": list(df.drop(columns=['status'], errors='ignore').columns)
}
with open("preprocessor.pkl", "wb") as f:
    pickle.dump(meta, f)

print("Preprocessing pipeline fitted and saved as 'preprocessor.pkl'")
print("Numeric columns:", len(num_cols))
print("Categorical columns:", len(cat_cols))

# ===== STEP 5: TRAIN/TEST SPLIT + BASELINE LOGISTIC REGRESSION =====
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import joblib
import pickle

# Load preprocessor
with open("preprocessor.pkl", "rb") as f:
    meta = pickle.load(f)
preprocessor = meta["preprocessor"]

# Prepare features and target
X = df.drop(columns=['status'])
y = df['status']

# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Transform data using preprocessor
X_train_trans = preprocessor.transform(X_train)
X_test_trans = preprocessor.transform(X_test)

# Train Logistic Regression baseline
lr = LogisticRegression(max_iter=2000, class_weight='balanced', random_state=42)
lr.fit(X_train_trans, y_train)

# Predictions
y_pred = lr.predict(X_test_trans)
y_proba = lr.predict_proba(X_test_trans)[:, 1]

# Evaluation
print("\nBaseline Logistic Regression Results:")
print(classification_report(y_test, y_pred, digits=4))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("ROC AUC:", round(roc_auc_score(y_test, y_proba), 6))

# Save model
joblib.dump(lr, "baseline_logistic_model.pkl")
print("\nBaseline model saved as 'baseline_logistic_model.pkl'")

# ===== STEP 6: FINAL XGBOOST MODEL TRAINING & EVALUATION =====
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import joblib
import pickle

# Load preprocessor again
with open("preprocessor.pkl", "rb") as f:
    meta = pickle.load(f)
preprocessor = meta["preprocessor"]

# Reuse the same train/test split as logistic regression
X_train_trans = preprocessor.transform(X_train)
X_test_trans = preprocessor.transform(X_test)

# Compute scale_pos_weight to balance classes
neg, pos = (y_train == 0).sum(), (y_train == 1).sum()
scale_pos_weight = neg / pos
print("scale_pos_weight =", round(scale_pos_weight, 2))

# Train XGBoost model
xgb = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    random_state=42,
    n_estimators=250,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.01,
    reg_lambda=1.0,
    scale_pos_weight=scale_pos_weight,
    n_jobs=-1
)

xgb.fit(X_train_trans, y_train)

# Evaluate
y_pred = xgb.predict(X_test_trans)
y_proba = xgb.predict_proba(X_test_trans)[:, 1]

print("\nFinal XGBoost Results:")
print(classification_report(y_test, y_pred, digits=4))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("ROC AUC:", round(roc_auc_score(y_test, y_proba), 6))

# Save model
joblib.dump(xgb, "xgb_final_model.pkl")
print("\nFinal XGBoost model saved as 'xgb_final_model.pkl'")

# Adjusted threshold finder with better distribution and test samples
import json, pickle, joblib, numpy as np, pandas as pd
from sklearn.model_selection import train_test_split

# Load artifacts
with open("preprocessor.pkl","rb") as f:
    meta = pickle.load(f)
preprocessor = meta["preprocessor"]
raw_order = meta.get("raw_feature_order", None)
model = joblib.load("xgb_final_model.pkl")

# Load cleaned dataset
df_all = pd.read_csv("cleaned_no_leak.csv")
X_all = df_all.drop(columns=['status'])
y_all = df_all['status']

X_train_df, X_test_df, y_train_df, y_test_df = train_test_split(
    X_all, y_all, test_size=0.2, random_state=42, stratify=y_all
)

# Helper align
def _align_input(df_input):
    df_copy = df_input.copy()
    if raw_order is None:
        return df_copy
    for col in raw_order:
        if col not in df_copy.columns:
            df_copy[col] = np.nan
    return df_copy[raw_order]

X_train_trans_all = preprocessor.transform(_align_input(X_train_df))
train_probs = model.predict_proba(X_train_trans_all)[:,1]
train_true = y_train_df.values

# ADJUSTED SEARCH with more lenient criteria for better distribution
t_low_candidates = np.linspace(0.25, 0.40, 31)   # 0.25 .. 0.40
t_high_candidates = np.linspace(0.55, 0.75, 41)  # 0.55 .. 0.75

best = None
for tl in t_low_candidates:
    for th in t_high_candidates:
        if th <= tl + 0.10:  # Require at least 10-point medium band
            continue
        low_mask = train_probs <= tl
        high_mask = train_probs > th

        # Require reasonable sample sizes
        if low_mask.sum() < 100 or high_mask.sum() < 100:
            continue

        pos_rate_low = train_true[low_mask].mean() if low_mask.sum()>0 else 0.0
        pos_rate_high = train_true[high_mask].mean() if high_mask.sum()>0 else 0.0

        # RELAXED business criteria for better distribution
        if pos_rate_low <= 0.20 and pos_rate_high >= 0.65:
            medium_width = th - tl
            # Prefer wider medium bands (20-30 points)
            width_score = abs(medium_width - 0.25)  # Target 25-point medium band

            if best is None or width_score < best['width_score']:
                medium_mask = (train_probs > tl) & (train_probs <= th)
                pos_rate_medium = train_true[medium_mask].mean() if medium_mask.sum()>0 else 0.0

                best = {
                    't_low': float(tl),
                    't_high': float(th),
                    'pos_rate_low': float(pos_rate_low),
                    'pos_rate_medium': float(pos_rate_medium),
                    'pos_rate_high': float(pos_rate_high),
                    'low_count': int(low_mask.sum()),
                    'medium_count': int(medium_mask.sum()),
                    'high_count': int(high_mask.sum()),
                    'width': medium_width,
                    'width_score': width_score
                }

# Fallback to percentiles if none found
if best is None:
    t_low = float(np.percentile(train_probs, 40))
    t_high = float(np.percentile(train_probs, 70))
    best = {
        't_low': t_low,
        't_high': t_high,
        'method': 'percentiles_40_70'
    }

# Save thresholds
thresholds = {"low": best['t_low'], "high": best['t_high']}
with open("thresholds.json","w") as f:
    json.dump(thresholds, f, indent=2)

print("=" * 60)
print("ADJUSTED THRESHOLDS - Better Distribution")
print("=" * 60)
print(f"\nChosen thresholds:")
print(f"  Low risk:    probability ≤ {thresholds['low']:.4f}")
print(f"  Medium risk: {thresholds['low']:.4f} < probability ≤ {thresholds['high']:.4f}")
print(f"  High risk:   probability > {thresholds['high']:.4f}")

if 'pos_rate_low' in best:
    print(f"\nPerformance on training data:")
    print(f"  Low risk:    {best['pos_rate_low']*100:5.1f}% default rate ({best['low_count']:,} loans, {best['low_count']/len(train_probs)*100:.1f}%)")
    print(f"  Medium risk: {best['pos_rate_medium']*100:5.1f}% default rate ({best['medium_count']:,} loans, {best['medium_count']/len(train_probs)*100:.1f}%)")
    print(f"  High risk:   {best['pos_rate_high']*100:5.1f}% default rate ({best['high_count']:,} loans, {best['high_count']/len(train_probs)*100:.1f}%)")
    print(f"  Medium band width: {best['width']:.4f} ({best['width']*100:.1f} percentage points)")

# Define bander using chosen thresholds
THR_LOW = thresholds['low']
THR_HIGH = thresholds['high']

def band_from_prob(prob):
    if prob > THR_HIGH:
        return "High"
    if prob > THR_LOW:
        return "Medium"
    return "Low"

# Helper predict
def preprocess_single(input_dict):
    df_ = pd.DataFrame([input_dict])
    aligned = _align_input(df_)
    return preprocessor.transform(aligned)

def predict_single_local(input_dict):
    X = preprocess_single(input_dict)
    prob = float(model.predict_proba(X)[0,1])
    pred = int(prob >= 0.5)
    return {"probability": round(prob,4), "prediction": pred, "risk_band": band_from_prob(prob)}

# CALIBRATED TEST SAMPLES - designed to hit each band based on training data analysis
# Find actual examples from each band to use as templates
low_indices = np.where(train_probs <= THR_LOW)[0]
medium_indices = np.where((train_probs > THR_LOW) & (train_probs <= THR_HIGH))[0]
high_indices = np.where(train_probs > THR_HIGH)[0]

# Sample one from each band
sample_low_idx = low_indices[len(low_indices)//2]  # Middle of low band
sample_med_idx = medium_indices[len(medium_indices)//2]  # Middle of medium band
sample_high_idx = high_indices[len(high_indices)//2]  # Middle of high band

# Convert to dictionaries
def row_to_dict(idx):
    row = X_train_df.iloc[idx]
    return row.to_dict()

sample_low = row_to_dict(sample_low_idx)
sample_medium = row_to_dict(sample_med_idx)
sample_high = row_to_dict(sample_high_idx)

print("\n" + "=" * 60)
print("TEST SAMPLES - Verification")
print("=" * 60)

result_low = predict_single_local(sample_low)
result_med = predict_single_local(sample_medium)
result_high = predict_single_local(sample_high)

print(f"\n1. LOW RISK Sample:")
print(f"   Loan: ${sample_low.get('loan_amount', 0):,.0f}, Income: ${sample_low.get('income', 0):,.0f}")
print(f"   Credit: {sample_low.get('credit_score', 0):.0f}, LTV: {sample_low.get('ltv', 0):.1f}%, DTI: {sample_low.get('dtir1', 0):.1f}%")
print(f"   → Probability: {result_low['probability']:.4f} | Band: {result_low['risk_band']}")

print(f"\n2. MEDIUM RISK Sample:")
print(f"   Loan: ${sample_medium.get('loan_amount', 0):,.0f}, Income: ${sample_medium.get('income', 0):,.0f}")
print(f"   Credit: {sample_medium.get('credit_score', 0):.0f}, LTV: {sample_medium.get('ltv', 0):.1f}%, DTI: {sample_medium.get('dtir1', 0):.1f}%")
print(f"   → Probability: {result_med['probability']:.4f} | Band: {result_med['risk_band']}")

print(f"\n3. HIGH RISK Sample:")
print(f"   Loan: ${sample_high.get('loan_amount', 0):,.0f}, Income: ${sample_high.get('income', 0):,.0f}")
print(f"   Credit: {sample_high.get('credit_score', 0):.0f}, LTV: {sample_high.get('ltv', 0):.1f}%, DTI: {sample_high.get('dtir1', 0):.1f}%")
print(f"   → Probability: {result_high['probability']:.4f} | Band: {result_high['risk_band']}")

# Verify all three bands are hit
bands_hit = {result_low['risk_band'], result_med['risk_band'], result_high['risk_band']}
if bands_hit == {"Low", "Medium", "High"}:
    print("\n✓ SUCCESS: All three risk bands correctly represented!")
else:
    print(f"\n⚠ WARNING: Only hit bands: {bands_hit}")
    print("   You may need to adjust sample characteristics further.")

print("\n" + "=" * 60)
print("Thresholds saved to thresholds.json")
print("=" * 60)

